# Generated by Django 5.2.4 on 2025-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('track', models.CharField(choices=[('cloud', 'Cloud'), ('network', 'Network'), ('computing', 'Computing')], max_length=50)),
                ('level', models.CharField(choices=[('hcia', 'HCIA'), ('hcip', 'HCIP'), ('hcie', 'HCIE')], max_length=4)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'exam_attempts',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'exam_questions',
            },
        ),
    ]
