# Generated by Django 5.2.4 on 2025-09-06 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='examattempt',
            table='exam_attempts',
        ),
        migrations.AlterModelTable(
            name='examquestion',
            table='exam_questions',
        ),
    ]
