# Generated by Django 5.2.4 on 2025-07-30 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='formation',
        ),
    ]
