# Generated by Django 5.2.4 on 2025-09-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examattempt_table_alter_examquestion_table'),
        ('questions', '0005_alternative_correctanswerssources'),
        ('users', '0005_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.alternative')),
                ('exam_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.examattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_answers',
            },
        ),
    ]
