# Generated by Django 5.2.4 on 2025-12-05 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'alternatives',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.CharField(choices=[('HCIA', 'Hcia'), ('HCIP', 'Hcip'), ('HCIE', 'Hcie')], max_length=4)),
                ('has_answer', models.BooleanField()),
                ('has_multiple_answers', models.BooleanField()),
                ('track', models.CharField(choices=[('Cloud', 'Cloud'), ('Network', 'Network'), ('Computing', 'Computing')], max_length=16)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswersSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='questions.alternative')),
            ],
            options={
                'db_table': 'correct_answers_sources',
            },
        ),
    ]
