# Generated by Django 5.2.4 on 2025-09-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='submmited_by',
            new_name='submmitted_by',
        ),
    ]
