# Generated by Django 5.2.4 on 2025-09-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_rename_submmited_by_question_submmitted_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='submmitted_by',
            new_name='submitted_by',
        ),
    ]
