# Generated by Django 5.2.4 on 2025-09-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_rename_submmitted_by_question_submitted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('HCIA', 'Hcia'), ('HCIP', 'Hcip'), ('HCIE', 'Hcie')], max_length=4),
        ),
        migrations.AlterField(
            model_name='question',
            name='track',
            field=models.CharField(choices=[('Cloud', 'Cloud'), ('Network', 'Network'), ('Computing', 'Computing')], max_length=16),
        ),
    ]
