# Generated by Django 5.2.4 on 2025-09-12 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_question_level_alter_question_track'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='questions.question')),
            ],
            options={
                'db_table': 'alternatives',
            },
        ),
        migrations.CreateModel(
            name='CorrectAnswersSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='questions.alternative')),
            ],
            options={
                'db_table': 'correct_answers_sources',
            },
        ),
    ]
