# Generated by Django 5.2.4 on 2025-09-17 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alternative_correctanswerssources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correctanswerssources',
            old_name='question',
            new_name='alternative',
        ),
    ]
