# Generated by Django 5.2.4 on 2025-12-05 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
            ],
            options={
                'db_table': 'alternative_submissions',
            },
        ),
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('track', models.CharField(choices=[('cloud', 'Cloud'), ('network', 'Network'), ('computing', 'Computing')], max_length=50)),
                ('level', models.CharField(choices=[('hcia', 'HCIA'), ('hcip', 'HCIP'), ('hcie', 'HCIE')], max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')])),
                ('weight', models.FloatField()),
                ('feedback', models.TextField()),
                ('has_answer', models.BooleanField(default=False)),
                ('has_multiple_answers', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_submissions',
            },
        ),
        migrations.CreateModel(
            name='CorrectSubmissionAnswersSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('alternative_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.alternativesubmission')),
            ],
            options={
                'db_table': 'correct_submission_answer_sources',
            },
        ),
    ]
