# Generated by Django 5.2.4 on 2025-09-11 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('track', models.CharField(choices=[('cloud', 'Cloud'), ('network', 'Network'), ('computing', 'Computing')], max_length=50)),
                ('level', models.CharField(choices=[('hcia', 'HCIA'), ('hcip', 'HCIP'), ('hcie', 'HCIE')], max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')])),
                ('weight', models.FloatField()),
                ('feedback', models.FloatField()),
                ('has_answer', models.BooleanField(default=False)),
                ('has_multiple_answers', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_submissions',
            },
        ),
    ]
