# Generated by Django 5.2.4 on 2025-09-12 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='feedback',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='CorrectSubmissionAnswersSources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('question_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.questionsubmission')),
            ],
            options={
                'db_table': 'correct_submission_answer_sources',
            },
        ),
    ]
