# Generated by Django 5.2.4 on 2025-12-05 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionsubmission',
            name='submitted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alternativesubmission',
            name='question_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.questionsubmission'),
        ),
    ]
