# Generated by Django 5.2.4 on 2025-09-12 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_alter_questionsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correctsubmissionanswerssources',
            name='question_submission',
        ),
        migrations.CreateModel(
            name='AlternativeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('question_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.questionsubmission')),
            ],
            options={
                'db_table': 'alternative_submissions',
            },
        ),
        migrations.AddField(
            model_name='correctsubmissionanswerssources',
            name='alternative_submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='submissions.alternativesubmission'),
            preserve_default=False,
        ),
    ]
