# Generated by Django 5.2.4 on 2025-12-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsubmission',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
